using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;

using Breeze.Sharp;

namespace Todo.Models
{
    public class StringKey : BaseEntity
    {
        public override void Initialize() 
        {
            var entityType = EntityAspect.EntityType;
            entityType.AutoGeneratedKeyType = AutoGeneratedKeyType.Identity;
        }

        [Key]
        public string Id                               // String-valued primary key
        {
            get { return GetValue<string>(); }
            set { SetValue(value); }
        }

        public string Description                      // Another property
        {
            get { return GetValue<string>(); }
            set { SetValue(value); }
        }
    }
}
